### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by garbrand**
Added a Docker file, so it can be containerised. Still TODO: pull out the config and pass this in using env vars.

### CODE REVIEW

**Comment by garbrand** [comment]
@aikomastboom : can you verify whether I'm on the right path here dockerizing this service?

**Comment by aikomastboom** [comment]
```

**Comment by garbrand** [comment]
I'll pull out the rest of configuration first.

**Comment by garbrand** [comment]
@aikomastboom - can you review this and merge if ok?

**Comment by aikomastboom** [comment]
you may want to log the teamcity endpoint the receiver is going to talk to at server startup.

**Comment by garbrand** [comment]
Added logging of Teamcity `receiver` will post to.

**Pull request merged**
